### ISSUE TITLE
Идея.

### ISSUE THREAD

**Issue by TrueMajner** [miceve/xerl-contribution#3]
Взять меня в разработку

**Comment by angrymouse** [comment]
Добрый день! 
Вы можете помогать разработке бота так: Создайте Fork этого репозитория, и создайте в своём fork-e свою комманду для бота, далее сделайте pull request в главную ветку этого репозитория. После вышеуказанных действий мы проверим вашу комманду на соответстиве нормам, и если она окажется полезной то мы добавим её в бота.
Удачи в разработке!
